feat: update doc

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,10 +1,9 @@
 name: Deploy
 
-# on:
-#   push:
-#     branches:
-#       - main
-on: pull_request
+on:
+  push:
+    branches:
+      - main
 
 jobs:
   # Publish documentation as github pages
@@ -30,43 +29,43 @@ jobs:
 
   # Create a github tag and release based on last commit and current python project version
   # Publish package to Pypi
-  # release:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
+  release:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-  #     - name: Install uv
-  #       uses: astral-sh/setup-uv@v6
+      - name: Install uv
+        uses: astral-sh/setup-uv@v6
 
-  #     - name: Check version
-  #       id: version
-  #       run: |
-  #         VERSION=$(uv version --short)
-  #         status=0
-  #         git tag -l | grep -P "^$VERSION$" || status=1
-  #         if [[ $status == 0 ]];
-  #         then
-  #           echo "::error::Tag $VERSION already exists. Please increase project version in pyproject.toml."
-  #           exit 1
-  #         fi
-  #         echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
-  #         echo "MESSAGE=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"
+      - name: Check version
+        id: version
+        run: |
+          VERSION=$(uv version --short)
+          status=0
+          git tag -l | grep -P "^$VERSION$" || status=1
+          if [[ $status == 0 ]];
+          then
+            echo "::error::Tag $VERSION already exists. Please increase project version in pyproject.toml."
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
+          echo "MESSAGE=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"
 
-  #     - name: Create release
-  #       uses: ncipollo/release-action@v1
-  #       with:
-  #         body: |
-  #           # Release ${{ steps.version.outputs.VERSION }}
+      - name: Create release
+        uses: ncipollo/release-action@v1
+        with:
+          body: |
+            # Release ${{ steps.version.outputs.VERSION }}
 
-  #           ${{ steps.version.outputs.MESSAGE }}
-  #         commit: main
-  #         tag: ${{ steps.version.outputs.VERSION }}
+            ${{ steps.version.outputs.MESSAGE }}
+          commit: main
+          tag: ${{ steps.version.outputs.VERSION }}
 
-  #     - name: Build
-  #       run: uv build
+      - name: Build
+        run: uv build
 
-  #     - name: Deploy to Pypi
-  #       run: uv publish --publish-url ${{ vars.PYPI_URL }} --token ${{ secrets.PYPI_TOKEN }}
+      - name: Deploy to Pypi
+        run: uv publish --publish-url ${{ vars.PYPI_URL }} --token ${{ secrets.PYPI_TOKEN }}
